### ISSUE TITLE
Admin: Sidebar is not displaying in About Us page and Products page

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#15]
![about us - poolside mindarie 2015-12-22 15-07-27](https://cloud.githubusercontent.com/assets/13309806/12014725/a3e579be-ace6-11e5-9c82-bdfc3ed6004c.png)

**Comment by kabirkhan123** [comment]
Products page design is updated.
