### ISSUE TITLE
Products page : Image shape is not implemented as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#25]
![products - poolside mindarie 2015-12-22 15-37-16](https://cloud.githubusercontent.com/assets/13309806/12014940/ca467632-ace9-11e5-8509-90e4c3d31ea3.png)

**Comment by kabirkhan123** [comment]
As per design implemented.
![img_31122015_114020](https://cloud.githubusercontent.com/assets/16079664/12061940/bcc3c7fe-afb8-11e5-8393-b697b52d5efa.png)
