### ISSUE TITLE
Home page (Welcom Section) :Text should be in three columns as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#29]
![welcome - poolside mindarie - poolside mindarie 2015-12-22 14-56-46](https://cloud.githubusercontent.com/assets/13309806/12015006/ce277746-acea-11e5-8962-b5e3dadeffbd.png)

**Comment by kabirkhan123** [comment]
As per the project scope revisions -Homepage content - change from 3 column layout to 1 column layout

https://projects.titanweb.com.au/public/index.php?path_info=projects/poolside-mindarie-pool-and-spa-pack1resp/tasks/24
![24- poolside mindarie pool spa - website build - p1 titan digital 2015-12-30 12-26-22](https://cloud.githubusercontent.com/assets/16079664/12047416/093abf20-aef1-11e5-893f-7de9ca8d7bf7.png)
