### ISSUE TITLE
Home page(Water testing section) : Link text should be one line as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#30]
![welcome - poolside mindarie - poolside mindarie 2015-12-22 15-01-59](https://cloud.githubusercontent.com/assets/13309806/12015035/4d894a3c-aceb-11e5-8d4b-2522d2b110af.png)

**Comment by kabirkhan123** [comment]
Implemented to two lines as per Knowledge base article.
