### ISSUE TITLE
Home page(Water testing section) : Title should cater one line as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#32]
![welcome - poolside mindarie - poolside mindarie 2015-12-22 14-58-50](https://cloud.githubusercontent.com/assets/13309806/12016045/f3b9a9ba-acfa-11e5-90f4-23d8dde046ae.png)

**Comment by kabirkhan123** [comment]
Implemented to two lines as per the knowledge base article.
