### ISSUE TITLE
Products: Message field border disappears after the clicking out of the pop up form.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#47]
Steps:
1. Open products page.
2. Fill up form properly.
3. Click anywhere outside the form so that the form disappears.
4. Click the button to open the form again.
![image](https://cloud.githubusercontent.com/assets/11186313/12228455/c6779bc4-b876-11e5-8766-3f201f675d72.png)

**Comment by roseliesromeo** [comment]
Issue is still reproducible following these steps:
![image](https://cloud.githubusercontent.com/assets/11186313/12500965/0066d1f4-c0f3-11e5-861e-a66f475fab51.png)

**Comment by kabirkhan123** [comment]
Can you provide the browser details?

**Comment by roseliesromeo** [comment]
Chrome
Steps:
1. Open Enquire Now form
2. Fill in the message field
3. Click outside the form
4. Click the Enquire Now button again.

![image](https://cloud.githubusercontent.com/assets/11186313/12506693/cc1467de-c12b-11e5-8e56-cb589921b299.png)

**Comment by kabirkhan123** [comment]
Pop up form is working fine .Please clear your cache once and check it.

**Comment by roseliesromeo** [comment]
Already cleared cache. Still got issue.
Chrome
Try following the step:
1. Click to open Enquire Now pop-up form
2. Fill in the message field
3. Click outside the form (to close the form)
4. Click the button to open Enquire Now pop-up form again.
![image](https://cloud.githubusercontent.com/assets/11186313/12570793/db8aa9c0-c415-11e5-8b19-227fe69a1294.png)
