### ISSUE TITLE
Equipment:  There is no ellipsis after the shortened description.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#57]
![image](https://cloud.githubusercontent.com/assets/11186313/12255572/00889dcc-b930-11e5-98a1-b06d8aee5fd7.png)

**Comment by kabirkhan123** [comment]
For Latest News page - ellipsis after the shortened description has been added.

**Comment by roseliesromeo** [comment]
How about for ellipsis listing page? Description is also shortened so it would be reasonable to add ellipses after the shortened text for consistency.
