### ISSUE TITLE
Equipment:  I didn't see from the scope that there should be category page for the equipment custom posts. The last time I checked there only equipment listing page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#64]

**Comment by kabirkhan123** [comment]
As discussion with the PM, added category page for the equipment custom posts.
https://projects.titanweb.com.au/public/index.php?path_info=projects/poolside-mindarie-pool-and-spa-pack1resp/tasks/27
