### ISSUE TITLE
Lead-in's : Lead-in's icons are not implemented as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Poolside-Mindarie-Pool-and-Spa#7]
![home - poolside mindarie - poolside mindarie 2015-12-22 13-42-41](https://cloud.githubusercontent.com/assets/13309806/11951191/b9777734-a843-11e5-8417-0aa8ba1975fa.png)

**Comment by kabirkhan123** [comment]
As per the scope, i have used awesome font for icon.
![16ee113ae331b5cc80ef8a11bb1e45db3ba30a331bdb101a69 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/16079664/12061428/9c97c712-afab-11e5-89b6-51f3dbd4fbbc.jpg)
